{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-9740",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "https://bugs.python.org/issue36276",
                "refsource": "MISC",
                "url": "https://bugs.python.org/issue36276"
            },
            {
                "refsource": "BID",
                "name": "107466",
                "url": "http://www.securityfocus.com/bid/107466"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-1ffd6b6064",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:1260",
                "url": "https://access.redhat.com/errata/RHSA-2019:1260"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-ec26883852",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://security.netapp.com/advisory/ntap-20190619-0005/",
                "url": "https://security.netapp.com/advisory/ntap-20190619-0005/"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-1] python3.4 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-2] python3.4 regression update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-7723d4774a",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/44TS66GJMO5H3RLMVZEBGEFTB6O2LJJU/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-7df59302e0",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2ORNTF62QPLMJXIQ7KTZQ2776LMIXEKL/"
            },
            {
                "refsource": "REDHAT",
                "name": "RHSA-2019:2030",
                "url": "https://access.redhat.com/errata/RHSA-2019:2030"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4127-2",
                "url": "https://usn.ubuntu.com/4127-2/"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2019:2131",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2019:2133",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html"
            },
            {
                "refsource": "UBUNTU",
                "name": "USN-4127-1",
                "url": "https://usn.ubuntu.com/4127-1/"
            }
        ]
    }
}