{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2019-16056",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "An issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugs.python.org/issue34155",
                "refsource": "MISC",
                "name": "https://bugs.python.org/issue34155"
            },
            {
                "url": "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/commit/8cb65d1381b027f0b09ee36bfed7f35bb4dec9a9"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-4954d8773c",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K4KZEFP6E4YPYB52AF4WXCUDSGQOTF37/"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190916 [SECURITY] [DLA 1925-1] python2.7 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/09/msg00019.html"
            },
            {
                "refsource": "MLIST",
                "name": "[debian-lts-announce] 20190916 [SECURITY] [DLA 1924-1] python3.4 security update",
                "url": "https://lists.debian.org/debian-lts-announce/2019/09/msg00018.html"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-50772cf122",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NF3DRDGMVIRYNZMSLJIHNW47HOUQYXVG/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-5dc275c9f2",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ER6LONC2B2WYIO56GBQUDU6QTWZDPUNQ/"
            },
            {
                "refsource": "FEDORA",
                "name": "FEDORA-2019-2b1f72899a",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E2HP37NUVLQSBW3J735A2DQDOZ4ZGBLY/"
            },
            {
                "refsource": "CONFIRM",
                "name": "https://security.netapp.com/advisory/ntap-20190926-0005/",
                "url": "https://security.netapp.com/advisory/ntap-20190926-0005/"
            }
        ]
    }
}