{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve-assign@distributedweaknessfiling.org",
      "DATE_ASSIGNED" : "2017-08-22T17:29:33.370843",
      "ID" : "CVE-2017-1000158",
      "REQUESTER" : "jaybosamiya@gmail.com",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "CPython",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "2.7.13 and older"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : ""
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "CPython (aka Python) up to 2.7.13 is vulnerable to an integer overflow in the PyString_DecodeEscape function in stringobject.c, resulting in heap-based buffer overflow (and possible arbitrary code execution)"
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "Integer Overflow"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "https://lists.debian.org/debian-lts-announce/2017/11/msg00035.html"
         },
         {
            "url" : "https://lists.debian.org/debian-lts-announce/2017/11/msg00036.html"
         },
         {
            "url" : "https://bugs.python.org/issue30657"
         },
         {
            "url" : "http://www.securitytracker.com/id/1039890"
         }
      ]
   }
}
